project_id_env: "CROWDIN_PROJECT_ID"
api_token_env: "CROWDIN_PERSONAL_TOKEN"
base_path: "."
base_url: "https://api.crowdin.com"
preserve_hierarchy: false

files:
  - source: 'lib/l10n/app_en.arb'
    translation: 'lib/l10n/app_%two_letters_code%.arb'

  - source: 'android/app/src/main/res/values/strings.xml'
    translation: 'android/app/src/main/res/values-%two_letters_code%/strings.xml'
